version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      - npm install next -g
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
       - npx next build
artifacts:
  files:
     - '**/*'